### ISSUE TITLE
Failure to compile with GHC 8.2 and latest Cabal packages

### ISSUE THREAD

**Issue by ndmitchell** [dysinger/no-http#4]
```
Main.hs:57:19: error:
    Ambiguous occurrence ‘option’
    It could refer to either ‘BasePrelude.option’,
                             imported from ‘BasePrelude’ at Main.hs:17:1-28
                             (and originally defined in ‘Data.Semigroup’)
                          or ‘Options.Applicative.option’,
                             imported from ‘Options.Applicative’ at Main.hs:39:7-12
                             (and originally defined in ‘Options.Applicative.Builder’)
   |
57 |                   option auto
   |                   ^^^^^^
```
